### PR TITLE
Update paths to follow instructions on README.md

### PR DESCRIPTION
**Pull request by ghumpire**
Hi, I followed the README.md instructions to run the demo but I found the following paths were wrong. Please verify whether you agree with this.

### CODE REVIEW

**Comment by sleep3r** [comment]
> Hi, I followed the README.md instructions to run the demo but I found the following paths were wrong. Please verify whether you agree with this.

Hi, Gabriel! Did you manage to run demo with this path changes?

**Comment by ghumpire** [comment]
Hey @sleep3r, no, it does not run the demo because later I faced this issue #4.

**Comment by sleep3r** [comment]
@ghumpire, I've just run it. I could share you my run.sh script via mail or telegram (which may be better).

**Comment by ghumpire** [comment]
@sleep3r Could you please paste your sh here or in #4? That would benefit others as well. Thanks!

**Comment by JiangWenPL** [comment]
We assume you would run those commands after `cd mmdetection` as we suggested in those examples.

**Pull request closed without merging**
